services:
  - type: web
    name: drug-interaction-checker
    env: python
    region: singapore  # アジアリージョンを選択
    buildCommand: pip install -r requirements.txt
    startCommand: python implementation.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: CLAUDE_API_KEY
        sync: false  # シークレット値として設定
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
    healthCheckPath: /docs  # FastAPIのSwagger UIを使用
    autoDeploy: true  # GitHubと連携時に自動デプロイを有効化 